# Generated by Django 3.2.8 on 2021-10-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20211011_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
